#!/bin/sh
set -eu

mkdir -p "$1"

jq -n \
	--arg id "${BUILD_ID:-}" \
	--arg name "${BUILD_NAME:-}" \
	--arg job_name "${BUILD_JOB_NAME:-}" \
	--arg pipeline_name "${BUILD_PIPELINE_NAME:-}" \
	--arg pipeline_instance_vars "${BUILD_PIPELINE_INSTANCE_VARS:-}" \
	--arg team_name "${BUILD_TEAM_NAME:-}" \
	--arg created_by "${BUILD_CREATED_BY:-}" \
	--arg url "${BUILD_URL:-}" \
	--arg url_short "${BUILD_URL_SHORT:-}" \
	--arg date $(date -u +"%Y-%m-%dT%H:%M:%SZ") \
	'{
		id: $id,
		name: $name,
		date: $date,
		job_name: $job_name,
		pipeline_name: $pipeline_name,
		pipeline_instance_vars: $pipeline_instance_vars,
		team_name: $team_name,
		created_by: $created_by,
		url: $url,
		url_short: $url_short
	}' > "$1/metadata.json"

for key in $(jq -r 'keys[]' "$1/metadata.json"); do
	jq -r --arg k "$key" '.[$k]' "$1/metadata.json" > "$1/$key"
done

jq '{version: .}' "$1/metadata.json"
